### ISSUE TITLE
Groups

### ISSUE THREAD

**Issue by pvizeli** [ggravlingen/pytradfri#124]
Is it possible to set color temp for group?

**Comment by ggravlingen** [comment]
It appears not. Instead you will have to dig into 9018 and pick up whatever light entities are in there before you alter color temp. This is raw data from one of my groups:
```
>>> print(api(groups[2]))
DEBUG:pytradfri.api.libcoap_api:Executing 192.168.0.129 get ['15004', 131075]
{
  "5850": 0,
  "5851": 0,
  "9001": "Kök",
  "9002": 1509923739,
  "9003": 131075,
  "9018": {
    "15002": {
      "9003": [
        65539
      ]
    }
  },
  "9039": 196614
}
``

**Comment by pvizeli** [comment]
Hmm the ikea android app suggest that it would work but look like he fake that function.

What you mean with `9018`?

**Comment by ggravlingen** [comment]
The gateway returns JSON-strings for each device as displayed in this file: https://github.com/ggravlingen/pytradfri/blob/master/tests/devices.py

By `9018` I mean the line in my reply above where it reads 9018. This node points to 15002, which is an attribute for HS_LINK (not found among constants, yet). 9003 is ATTR_ID which points to 65539, which is the gateway's internal number for one of my bulbs.

**Comment by ggravlingen** [comment]
Errata: I added the missing constant.

**Comment by ggravlingen** [comment]
@pvizeli any further comments here?

**Comment by pvizeli** [comment]
I think we can close it.

Thanks for support :+1:

**Comment by infernix** [comment]
Are we assuming the IKEA app "fakes" group temperature/color control and instead sets them for individual lights within the group? Or do we know for sure?

And is that something we should aim to emulate in pytradfri then? I can imagine it'd be more efficient (read: faster synchronicity when changing) when pytradfri handles it for large groups instead of any components using pytradfri.

**Comment by lwis** [comment]
That's the running theory, the way groups work in the coap API today is that they don't broadcast events. however, updating a bulb in a group updates the group in the app. So we're either missing something, or IKEA is only using the group functionality for switching lights on/off, not for events.

**Comment by ReX1983** [comment]
Hi guys, is there any update on setting the color for a group? I have 20 downlights in a group and changing the color temperature via the home assistant group is a poor experience.

**Comment by infernix** [comment]
@ReX1983 if you are using traditional groups, you should switxh to https://www.home-assistant.io/components/light.group/

**Comment by ReX1983** [comment]
@infernix, I am using Light Group but the problem is that the lights don't get updated simultaneously. 

There is always a noticeable delay that is quite unpleasant if you have many lights in the same group. Possibly because the gateway receives 20+ commands in one go and takes a while to propagate them to the lights over the ZigBee network.

One more side effect is that the color temperature value in the Home Assistant UI jumps up and down for a some time, before stabilizing to the target temperature (since it is the average of the color temp value in the group).

**Comment by infernix** [comment]
I see the same but all 6 lights here change temp in around 100-200ms it seems. How big of a delay do you get? And i assume tradfri app is instantaneous?

**Comment by ReX1983** [comment]
From the tradfri app is instantaneous (I am really impressed by how quickly it reacts to changes), from HA it takes up to 3 seconds (I would say).

It is not the case for brightness, that is instantaneous in HA since supported by the tradfri native group.

**Comment by infernix** [comment]
Weird, it shouldn't be that slow. Have you checked logs? Enable debugging with:

```
logger:
        default: warning
        logs:
                homeassistant.components.tradfri: debug
                pytradfri: debug
```

**Comment by ReX1983** [comment]
@infemix, let me try to enable the debug and look at it. I will check about the async/sync modes. 

@Iwis, I would like to use the trådfri native group but it doesn't support color temperature. When using the native group the update of the lights in the group is simultaneous.

What I have done is creating a template light in HA: the group status is taken from the HA light group (because the native group status is not updated if the lights are controlled via the trådfri dimer) and the on/off and brightness commands are sent to the native group, ensuring simultaneous on/off and brightness update. 
The only missing thing is the color, that is not exposed by the native trådfri group. 

I have noticed a new, more annoying issue: when I turn on/off the trådfri native group, sometimes some of the lights of the group don't get updated in HA. E.g. I turn off the trådfri group via HA, all the lights go off but in HA some of them remain on. I need to individually turn them off in HA otherwise they can stay in the wrong state till the next command. It seems that the trådfri gateway doesn't notify HA the status update.

**Comment by lwis** [comment]
If the app allows it, then there's an endpoint for it that we've missed.

I understand that HA doesn't update native group statuses correctly (this is actually another issue with native groups that we have).

I'm thinking someone needs to sit down and sniff the tradfri app to understand the COAP calls it's making to the gateway, we need to give native groups some love.

You'll never get good performance out of light groups in HA, so there's little point in debugging it.

**Comment by ReX1983** [comment]
I agree with you, I think the HA groups are a fallback solution, but it isn't the ideal choice. 

On a different note, I am afraid I have other bad news: when I control the downlights using the Tradfri controller, the status reported in HA becomes erratic: some lights remain off in HA while they are actually on and some other remain on. I am still able to turn on and off lights from HA but the state doesn't get updated anymore.

It looks like that the only solution when the problem starts is to reboot the tradfri gateway (I have not check if HA reboot would solve it).

Have you seen something similar?

**Comment by Lakitna** [comment]
I've had some issues with the COAP subscription, but that could be my implementation.

I've noticed that if you send a big bundle of commands to the gateway at once it will not always correctly notify subscribed nodes of a change. You should be able to check this in HA if you follow the logs while changing lamps. If there are update messages missing in HA it's probably because of the update notification are not being sent by the gateway.

Restarting HA should fix it too since it will most likely poll (not subscription based) the gateway for the current data. A dirty fix could be to keep the subscription and periodically poll the gateway.

**Comment by ReX1983** [comment]
Slightly different issue in my case: when I send a single command to the native trådfri group, the status of the individual lights is not updated in HA. But if I send 17 individual commands to the lights (by using the HA light group) the lights are correctly updated in HA.

This is annoying because the HA light groups have delays (as discussed above) but at the same time the native group status is not updated correctly, so I need to rely on the status of the individual lights, via the HA light groups. 

I thought the problem was limited to HA but then I saw the lights as not updated also in the trådfri android app. But let me come back on this later today.

**Comment by lwis** [comment]
I don't want to conflate this issue, if there are issues with status
updates we should consolidate them into a new issue.

This issue is just for group temperature/colour support.

**Comment by ReX1983** [comment]
You are right. I will do some investigation and then report the other issue.

Back on topic: it would be nice to control the color temperature of a native group. The Android app allows to do it, so there should be a way to send a command at group level.
