### ISSUE TITLE
Inconsistent use of 

### ISSUE THREAD

**Issue by ggsubs** [ggravlingen/pytradfri#133]
Readme advocates the use of PSK, but examples fall back to use the Security Key.

"Please always use the PSK when communicating with the gateway."
"KEY is written on the back of your IKEA Tradfri Gateway."

As in https://github.com/home-assistant/home-assistant/issues/10252 all of us should use the PSK.

Expected: clarity in the Readme.

**Comment by Lakitna** [comment]
I think it should also be clarified in the example files. 

The examples only require the KEY when there is no PSK/IDENTITY pair yet for the given IP. But since you have to add the KEY the first time, many people will just assume adding the KEY all the time is good practice.

Maybe it's better to use `input()` instead of arguments to input the KEY? That would stop users from adding the KEY all the time.

I could write this if we want to do this.

**Comment by ggravlingen** [comment]
@ggsubs and @Lakitna I agree that there is some ambiguity in the docs regarding KEY and PSK. Please feel free to submit PRs suggesting improvements!
