### ISSUE TITLE
Address lights through name instead of index

### ISSUE THREAD

**Issue by hanpal** [ggravlingen/pytradfri#35]
I lost contact with my gatateway and rebooted. All devices were present but the index numbers had changed, the last bulb added was now at index 0 and my scripts stopped working. I'm now looping through the lights to check for name but it woud be better to be able to address through name and not only by index number. Alternatively adding a utility function that translates from name to index (-1 or similar if not found), to be used instead of using index number. Simplifies the code in the user script.

**Comment by lwis** [comment]
Please feel free to raise a PR :+1:

**Comment by balloob** [comment]
Use the `gateway.get_device(device_id)` method to fetch a specific device each time.

Getting by name is difficult to add. It would mean that we need to return a command that fetches all the devices and then filters them. Since we allow fetching a specific device by id, I don't think that we should add this to pytradfri.
